---

- name: common
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml

  roles:
    - common

- name: web
  hosts: web
  become: true
  vars_files:
    - vars/vars.yml

  roles:
    - web

- name: db
  hosts: db
  become: true
  vars_files:
    - vars/vars.yml

  roles:
    - db
