---
# install mariadb

- name: add MariaDB repo
  template:
    src: templates/mariadb.repo.j2
    dest: /etc/yum.repos.d/mariadb.repo

- name: install MariaDB
  dnf: name={{ item }} state=latest
  with_items:
    - MariaDB-server
    - MariaDB-client

- service:
    name: mariadb
    enabled: yes
    state: started