---
# install apache

- name: install httpd packages
  dnf: name={{ item }} state=latest
  with_items:
    - httpd
    - httpd-tools
    - mod_ssl

- service:
    name: httpd
    enabled: yes
    state: started

- name: Create web folder on storage volume
  file:
    path: /mnt/storage/web
    state: directory

- name: link web directory to storage volume
  file:
    src: /mnt/storage/web
    dest: /var/www/html
    owner: root
    group: root
    force: yes
    state: link

- name: Set selinux context on symlinked directory
  community.general.sefcontext:
    target: /mnt/storage/web
    setype: httpd_sys_content_t
    reload: yes
    state: present

- name: apply selinux file context
  command: restorecon -irv /mnt/storage/web

- name: allow httpd to connect to the database
  command: setsebool -P httpd_can_network_connect_db 1

- name: allow httpd to connect to the internet
  command: setsebool -P httpd_can_network_connect 1

- name: create vhosts directory
  file:
    path: /etc/httpd/vhosts
    state: directory

- name: add vhost config file to conf.d
  template:
    src: templates/vhosts.conf.j2
    dest: /etc/httpd/conf.d/vhosts.conf

- name: add vhost
  template:
    src: templates/website.conf.j2
    dest: "/etc/httpd/vhosts/{{ domain_name }}.conf"