---
- name: apply remi repo key
  rpm_key:
    state: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018

- name: enable remi repo
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm

- name: enable php module
  command: dnf module enable -y php:remi-8.0

- name: install php packages
  dnf: name={{ item }} state=latest
  with_items:
    - php-common
    - php-devel
    - php-fpm
    - php-opcache
    - php-mysqlnd
    - php-cli
    - php-intl
    - php-pdo
    - php-gd
    - php-json
    - php-pecl-xdebug
    - php-xml
    - php-xmlrpc
    - php-mbstring
    - php-pecl-imagick
    - php-pecl-zip

- service:
    name: php-fpm
    enabled: yes
    state: started