---

- name: enable ius repo
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm

- name: install php packages
  yum: name={{ item }} state=latest
  with_items:
    - php73-common
    - php73-devel
    - php73-fpm
    - php73-opcache
    - php73-mysqlnd
    - php73-cli
    - php73-intl
    - php73-pdo
    - php73-gd
    - php73-json
    - php73-pecl-xdebug
    - php73-xml
    - php73-xmlrpc
    - php73-mbstring

- template:
    src: php.conf.j2
    dest: /etc/httpd/conf.d/php.conf
